version: "3"
networks:
    eventdriven:

services:
    rabbitmq:
        image: "rabbitmq"
        container_name: "rabbitmq"
        ports:
            - "5672:5672"
        networks:
            eventdriven:
        restart:
            "always"
    logger:
        build: 
            context: .
            dockerfile: ./utility/logger/Dockerfile.dev
        container_name: "logger"
        networks:
            eventdriven:
        restart:
            "always"
